const model = {
  //app
  // mainView, addImageView, contactView, adminContactView, collabView, loginView
  state: "mainView",

  //input

  inputs: {
    login: {
      password: "",
      username: "",
    },

    user: {
      search: "",
      pictureComment: {
        email: "",
        user: "",
        comment: "",
        date: "",
      },
      userFilter: [],
      collabArray: [],
    },
    admin: {
      addPic: {
        img: "",
        projectName: "",
        projectNumber: 0,
        title: "",
        description: "",
        artist: "",
        category: [],
        projects: [],
      },
      editProfile: {
        aboutCreator: "",
        aboutPicture: "",
        title: "",
        creatorSoMeLink: [
          { link: "" },
          { link: "" },
          { link: "" },
          { link: "" },
        ],
      },
    },
  },

  //data
  isMobile: null,
  runOnce: false,
  areYouSure: false,
  areYouSureImg: false,
  isAdmin: false,
  filterMenu: true,
  filterView: false,
  filterChecked: false,
  logo: "IMG/Signatur.png",
  backLogo: "IMG/ICONS/tilbake.png",

  modal: {
    addCommentOpen: false,
    commentFieldOpen: false,
    descriptionFieldOpen: false,
    showModal: false,
    modalPictures: "",
    slideIndex: 1,
    modalComments: "",
    modalDescription: "",
  },
  filter: [
    { cat: "Architecture", checked: false },
    { cat: "Building", checked: false },
    { cat: "Completed", checked: false },
    { cat: "Collaboration", checked: false },
    { cat: "Surrealism", checked: false },
    { cat: "Art", checked: false },
    { cat: "Exhibition", checked: false },
    { cat: "Collage", checked: false },
    { cat: "Digital", checked: false },
    { cat: "Sculpture", checked: false },
    { cat: "3Dprint", checked: false },
    { cat: "3Dmodeling", checked: false },
    { cat: "Utopic", checked: false },
  ],
  projects: [
    { projectName: "Home Atelier", projectNumber: 1 },
    { projectName: "Exhibition", projectNumber: 2 },
    { projectName: "Digital Collage", projectNumber: 3 },
    { projectName: "3D Print", projectNumber: 4 },
    { projectName: "Architectural projects", projectNumber: 5 },
  ],
  creator: {
    role: "Admin",
    password: "1234",
    email: "jarand@epost.no",
    tlf: 12345678,
    aboutPicture: {
      picture: "IMG/Jarand_img.jpg",
      editMode: false,
    },
    title: "Arkitekt",
    name: "Jarand Midtgaard",
    aboutCreator: {
      about:
        "Jeg er en arkitekt og kunstner fra Sandefjord",
      editMode: false,
    },
    creatorSoMelinks: {
      links: [
        {
          media: "Facebook",
          logoimg: "IMG/ICONS/facebook.png",
          link: "https://nb-no.facebook.com/",
        },
        {
          media: "SnapChat",
          logoimg: "IMG/ICONS/snapchat.png",
          link: "https://www.snapchat.com/",
        },
        {
          media: "Twitter",
          logoimg: "IMG/ICONS/twitter.png",
          link: "https://twitter.com/home?",
        },
        {
          media: "Instagram",
          logoimg: "IMG/ICONS/instagram.png",
          link: "https://www.instagram.com/",
        },
      ],
      editMode: false,
    },
  },

  SoMelinks: [
    {
      media: "Facebook",
      logoimg: "IMG/ICONS/facebook.png",
      link: "https://nb-no.facebook.com/",
    },
    {
      media: "SnapChat",
      logoimg: "IMG/ICONS/snapchat.png",
      link: "https://www.snapchat.com/",
    },
    {
      media: "Twitter",
      logoimg: "IMG/ICONS/twitter.png",
      link: "https://twitter.com/home?",
    },
    {
      media: "Instagram",
      logoimg: "IMG/ICONS/instagram.png",
      link: "https://www.instagram.com/",
    },
  ],

  pictures: [
    {
      img: "IMG/PICTURES/Pro1_1.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 1",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed"],
      comments: [
        {
          email: "somemail@dom.com",
          user: "Knut Arild",
          comment: "Dette var lekkert! 10/10.",
          date: "15/2 - 23",
        },
      ],
    },
    {
      img: "IMG/PICTURES/Pro1_2.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 2",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed"],
      comments: [ {
        email: "somemail@dom.com",
        user: "Cathrine",
        comment: "Så flott!",
        date: "15/2 - 23",
      },],
    },
    {
      img: "IMG/PICTURES/Pro1_3.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 3",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed", "Collaboration"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_1.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 1",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_2.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 2",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_3.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 3",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "Art",
        "Exhibition",
        "Collaboration",
      ],
      comments: [],
    },

    {
      img: "IMG/PICTURES/Pro3_1.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 1",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro3_2.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 2",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital"],
      comments: [ {
        email: "somemail@dom.com",
        user: "Ståle",
        comment: "Vireklig pent! Kreativt!",
        date: "15/2 - 23",
      },],
    },
    {
      img: "IMG/PICTURES/Pro3_3.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 3",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital", "Collaboration"],
      comments: [],
    },

    {
      img: "IMG/PICTURES/Pro4_1.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 1",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro4_2.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 2",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro4_3.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 3",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "Sculpture",
        "3Dprint",
        "Collaboration",
      ],
      comments: [ {
        email: "somemail@dom.com",
        user: "Joakim",
        comment: "Kreativt!",
        date: "15/2 - 23",
      },],
    },

    {
      img: "IMG/PICTURES/Pro5_1.JPG",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 1",
      description: "",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "3Dmodeling",
        "Utopic",
        "Collaboration",
      ],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro5_2.jpg",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 2",
      description: "",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "3Dmodeling", "Utopic"],
      comments: [ {
        email: "somemail@dom.com",
        user: "Nils",
        comment: "Fantastisk! Har du laget dette selv?",
        date: "15/2 - 23",
      },],
    },
    {
      img: "IMG/PICTURES/Pro5_3.JPG",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 3",
      description: "",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "3Dmodeling",
        "Utopic",
        "Collaboration",
      ],
      comments: [],
    },
  ],
};
