const model = {
  //app
  // mainView, adminView, addImageView, contactView, adminContactView, collabView, loginView
  state: "mainView",

  //input

  inputs: {
    login: {
      password: "",
      username: "",
    },

    user: {
      search: "",
      pictureComment: { comment: "", userEmail: "" },
      userFilter: [],
    },
    admin: {
      addPic: {
        img: "",
        title: "",
        description: "",
        artist: "",
        category: [],
      },
      editProfile: {
        aboutCreator: "",
        aboutPicture: "",
        title: "",
        creatorSoMeLink: "",
      },
    },
  },

  //data

  userMenu: ["Filtrering", "Kontakt", "Samarbeidsprosjekter"],
  adminMenu: ["Rediger filtrering", "Admin side", "Logg ut"],
  filter: [
    { cat: "Architecture", checked: false },
    { cat: "Building", checked: false },
    { cat: "Completed", checked: false },
    { cat: "Project1", checked: false },
    { cat: "Collaboration", checked: false },
    { cat: "Surrealism", checked: false },
    { cat: "Art", checked: false },
    { cat: "Exhibition", checked: false },
    { cat: "Collage", checked: false },
    { cat: "Digital", checked: false },
    { cat: "Sculpture", checked: false },
    { cat: "3Dprint", checked: false },
    { cat: "3Dmodeling", checked: false },
    { cat: "Utopic", checked: false },
  ],
  creator: {
    role: "Admin",
    password: "1234",
    email: "fakeEmail@mail.com",
    tlf: 12345678,
    aboutPicture: "IMG/ProfilePicture.jpeg",
    title: "Arkitekt",
    name: "Jarand Midtgaard",
    aboutCreator:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      creatorSoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },

    
    pictures: [
    {
      img: "IMG/PICTURES/Pro1_1.jpg",
      toggled: false,
      picId: 001,
      title: "Project 1 - Home Atelier 1",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed", "Collaboration",],
      comments: [{ user: "Knut Arild", comment: "Dette var lekkert! 10/10." }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro1_2.jpg",
      toggled: false,
      picId: 002,
      title: "Project 1 - Home Atelier 2",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed", "Collaboration",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro1_3.jpg",
      toggled: false,
      picId: 003,
      title: "Project 1 - Home Atelier 3",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed", "Collaboration",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro2_1.jpg",
      toggled: false,
      picId: 003,
      title: "Project 2 - Exhibition 1",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro2_2.jpg",
      toggled: false,
      picId: 003,
      title: "Project 2 - Exhibition 2",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro2_3.jpg",
      toggled: false,
      picId: 003,
      title: "Project 2 - Exhibition 3",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },

    {
      img: "IMG/PICTURES/Pro3_1.jpg",
      toggled: false,
      picId: 004,
      title: "Project 3 - Digital Collages 1",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro3_2.jpg",
      toggled: false,
      picId: 005,
      title: "Project 3 - Digital Collages 2",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro3_3.jpg",
      toggled: false,
      picId: 006,
      title: "Project 3 - Digital Collages 3",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },

    {
      img: "IMG/PICTURES/Pro4_1.jpg",
      toggled: false,
      picId: 007,
      title: "Project 4 - Sculptures 1",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro4_2.jpg",
      toggled: false,
      picId: 007,
      title: "Project 4 - Sculptures 2",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro4_3.jpg",
      toggled: false,
      picId: 007,
      title: "Project 4 - Sculptures 3",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },

    {
      img: "IMG/PICTURES/Pro5_1.JPG",
      toggled: false,
      picId: 007,
      title: "Project 5 - Architectural unbilt projects 1",
      description: "",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "3Dmodeling", "Utopic",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro5_2.jpg",
      toggled: false,
      picId: 007,
      title: "Project 5 - Architectural unbilt projects 2",
      description: "",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "3Dmodeling", "Utopic",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
    {
      img: "IMG/PICTURES/Pro5_3.JPG",
      toggled: false,
      picId: 007,
      title: "Project 5 - Architectural unbilt projects 3",
      description: "",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "3Dmodeling", "Utopic",],
      comments: [{ user: "", comment: "" }],
      SoMelinks: [
        { media: "Facebook", logoimg: "", link: "" },
        { media: "SnapChat", logoimg: "", link: "" },
        { media: "Twitter", logoimg: "", link: "" },
        { media: "Instagram", logoimg: "", link: "" },
      ],
    },
  ],
  areYouSure: false,
  logo: "IMG/Signatur.png",
  backLogo: "IMG/ICONS/tilbake.png",
};
